name: Build Universal Unlocked APK (Release)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Inject Pro Upgrades Automatically
        run: |
          FILE="myExpenses/src/main/java/org/totschnig/myexpenses/util/licence/LicenceHandler.kt"
          sed -i 's/const val TRIAL_DURATION_DAYS = 60L/const val TRIAL_DURATION_DAYS = 99999L/g' $FILE
          sed -i 's/(this.licenceStatus?.compareTo(licenceStatus) ?: -1) >= 0/true/g' $FILE

      - name: Build Universal Release APK (Unsigned)
        run: ./gradlew :myExpenses:packageExternReleaseUniversalApk

      # خطوة إضافية لطباعة مكان الملف الدقيق داخل السجلات
      - name: Find all APKs (For Debugging)
        run: find . -type f -name "*.apk"

      - name: Upload All Found APKs
        uses: actions/upload-artifact@v4
        with:
          name: MyExpenses-Universal-Release-Unsigned
          # هذا هو التعديل السحري الذي سيبحث في كل مكان
          path: '**/*.apk'
